### ISSUE TITLE
TypeError: 'IndirectReference' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by kirankumarsingh** [maxpmaxp/pdfreader#20]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-2faa8dfdb330> in <module>
----> 1 viewer = SimplePDFViewer(fd)

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/viewer/simple.py in __init__(self, *args, **kwargs)
     60 
     61     def __init__(self, *args, **kwargs):
---> 62         super(TextOperatorsMixin, self).__init__(*args, **kwargs)
     63         self.bracket_commands_stack = [] # one day we may start support BX/EX, MDC/BMC/EMC.
     64                                          # BI/EI comes as a part of ContentParser due to inline image object nature

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/viewer/pdfviewer.py in __init__(self, fobj)
    181         self.current_page_number = None
    182         self.doc = PDFDocument(fobj)
--> 183         super(PDFViewer, self).__init__(None, Resources(), self.graphics_state_stack_class())
    184 
    185     @property

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/viewer/pdfviewer.py in __init__(self, stream, resources, gss)
     37         self.resources = resources
     38         self.stream = stream
---> 39         self.on_document_load()
     40 
     41     def get_handler_name(self, obj, stage):

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/viewer/pdfviewer.py in on_document_load(self)
    245         super(PDFViewer, self).on_document_load()
    246         self.current_page_number = 1
--> 247         self.navigate(self.current_page_number)
    248 
    249     def before_navigate(self, n):

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/viewer/pdfviewer.py in navigate(self, n)
    205         self.before_navigate(n)
    206         self.current_page_number = n
--> 207         self.after_navigate(n)
    208 
    209     def next(self):

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/viewer/simple.py in after_navigate(self, n)
    180         name = op.args[0]
    181         xobj = self.resources.XObject.get(name)
--> 182         if not xobj:
    183             logging.warning("Can't locate XObject {}".format(name))
    184         else:

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/viewer/pdfviewer.py in after_navigate(self, n)
    253         self.canvas.reset()
    254         self.gss = GraphicsStateStack()
--> 255         self.resources = self.get_resources()
    256 
    257         # get content stream

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/viewer/pdfviewer.py in get_resources(self)
    238 
    239     def get_resources(self):
--> 240         return Resources.from_page(self.current_page)
    241 
    242     # Events

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/viewer/resources.py in from_page(cls, page, resources_stack)
     47                     if entry not in kwargs:
     48                         kwargs[entry] = dict()
---> 49                     for k, v in dict_or_array.items():
     50                         kwargs[entry][k] = v
     51                 elif isinstance(dict_or_array, Array):

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/types/objects.py in items(self)
    113 
    114     def items(self):
--> 115         return [(k, self[k]) for k in super(DictBasedObject, self).keys()]
    116 
    117     def pop(self, i, **kwargs):

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/types/objects.py in <listcomp>(.0)
    113 
    114     def items(self):
--> 115         return [(k, self[k]) for k in super(DictBasedObject, self).keys()]
    116 
    117     def pop(self, i, **kwargs):

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/types/objects.py in __getitem__(self, item)
     89             return self._cache[item]
     90         obj = super(DictBasedObject, self).__getitem__(item)
---> 91         obj = self.doc.build(obj, lazy=True)
     92         self._cache[item] = obj
     93         return self._cache[item]

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/document.py in build(self, obj, visited, lazy)
     57                 visited.append(obj)
     58                 on_return = visited.pop
---> 59                 obj = self.obj_by_ref(obj)
     60 
     61         # resolve subsequent references for Arrays, Dictionaries and Streams

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/document.py in obj_by_ref(self, objref)
    134     def obj_by_ref(self, objref):
    135         obj = self.locate_object(objref.num, objref.gen)
--> 136         return obj_factory(self, obj)
    137 
    138     def deep_obj_by_ref(self, obj, maxdepth=100):

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/types/objects.py in obj_factory(doc, obj)
    142         klass = ArrayBasedObject
    143 
--> 144     return klass(doc, obj) if klass else obj
    145 
    146 

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/types/objects.py in __init__(self, doc, lst)
     69         # ToDo: this must be lazier thing.
     70         # Need to build objects only on access attempt only. For example: a.index, a[i], a[1:2] etc.
---> 71         lst = [self.doc.build(obj, lazy=True) for obj in lst]
     72         super(ArrayBasedObject, self).__init__(lst)
     73 

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/types/objects.py in <listcomp>(.0)
     69         # ToDo: this must be lazier thing.
     70         # Need to build objects only on access attempt only. For example: a.index, a[i], a[1:2] etc.
---> 71         lst = [self.doc.build(obj, lazy=True) for obj in lst]
     72         super(ArrayBasedObject, self).__init__(lst)
     73 

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/document.py in build(self, obj, visited, lazy)
     57                 visited.append(obj)
     58                 on_return = visited.pop
---> 59                 obj = self.obj_by_ref(obj)
     60 
     61         # resolve subsequent references for Arrays, Dictionaries and Streams

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/document.py in obj_by_ref(self, objref)
    133 
    134     def obj_by_ref(self, objref):
--> 135         obj = self.locate_object(objref.num, objref.gen)
    136         return obj_factory(self, obj)
    137 

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/document.py in locate_object(self, num, gen)
    108                 try:
    109                     self.parser.reset(xre.offset)
--> 110                     self.parser.indirect_object()
    111                 except ParserException:
    112                     pass

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/parsers/document.py in indirect_object(self)
    398         obj = super(RegistryPDFParser, self).indirect_object()
    399         # handle all known indirect objects
--> 400         self.on_parsed_indirect_object(obj)
    401         return obj
    402 

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/parsers/document.py in indirect_object(self)
     54 
     55         self.maybe_spaces_or_comments()
---> 56         val = self.object()
     57         self.maybe_spaces_or_comments()
     58 

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/parsers/base.py in object(self)
    627         else:
    628             self.on_parser_error("Unexpected token")
--> 629         return val
    630 
    631     def indirect_reference(self):

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/parsers/base.py in dictionary_or_stream_or_hexstring(self)
    332             self.maybe_spaces_or_comments()
    333             if self.current == b's':
--> 334                 val = self._stream(val)
    335         elif self.is_hex_digit or self.is_whitespace:
    336             # < 09FF> is possible

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/parsers/base.py in _stream(self, d)
    430         # According to the spec EOL should be afterthe data and before endstream
    431         # But some files do not follow this.
--> 432         #
    433         # See data/leesoil-cases-2.pdf
    434         #

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/parsers/base.py in read(self, n)
     32 
     33     def read(self, n):
---> 34         return self.buffer.read(n)
     35 
     36     def get_state(self):

/Volumes/KiranDAT/anaconda3/lib/python3.7/site-packages/pdfreader/buffer.py in read(self, n)
    164 
    165     def read(self, n):
--> 166         return b''.join([self.next() for _ in range(n)])
    167 
    168     @property

TypeError: 'IndirectReference' object cannot be interpreted as an integer

**Comment by maxpmaxp** [comment]
@kirankumarsingh Could you attach you PDF please?

**Comment by maxpmaxp** [comment]
@kirankumarsingh Could you try 0.1.4rc1 from the master branch please?

**Comment by maxpmaxp** [comment]
@kirankumarsingh The issue duplicates #34 . See the discussion. Closing this one.

**Comment by maxpmaxp** [comment]
@kirankumarsingh Fixed in v 0.1.4
