### ISSUE TITLE
Regular expressions: review and reduce usage

### ISSUE THREAD

**Issue by maxpmaxp** [maxpmaxp/pdfreader#32]
Review and reduce usage of regular expressions in parsers.

**Comment by SanJJ1** [comment]
Just curious, why would you like to reduce regex?

**Comment by maxpmaxp** [comment]
@SanJJ1 Thank you for the comment. I reviewed the code and saw that I used `re` for parsing PDF header only apparently. Reducing this brings no value. Closing the issue.
