### ISSUE TITLE
Extract Images and Text.

### ISSUE THREAD

**Issue by Red-Fibre-Phoenix** [maxpmaxp/pdfreader#55]
So far I can do both using PDFDocument and SimplePDFViewer. The problem I have is finding out where I should load a PDF into a PDFDocument to get the images or a SimplePDFViewer to get the text. 

What I need to do is load it once, to see if I need to use an image extraction or text extraction tool. And then I can load the appropriate Object but by doing it seems more work to laod it once only to load it again. If the page in viewing has both text and images it means im doing to have to load the document 3 times.

Is there a way to get the Images and text from a document while also keeping the 'Special PDF parameters' out of the text? Im aware of the to_Pillow() method but again I can only use that with PDFDocument and not SimplePDFViewer which I extract the text with.

**Comment by maxpmaxp** [comment]
@Red-Fibre-Phoenix First of all you don't need to load the doc 2 or 3 times. One load is enough, then use either objects navigation for  PDFDocument or pages navigation with SimplePDFViewer.

Then, you can use SimplePDFViewer [to extract images and texts].(https://pdfreader.readthedocs.io/en/latest/tutorial.html#extracting-page-images)
 
So what is the difference between PDFDocument and SimplePDFViewer?

1. PDFDocument allows you to access raw document: file structure, document structure, objects, content-streams. It knows nothing about how to "render" content on a page. It's a kind of low-level tool.

2. SimplePDFViewer - is a high level tool, which takes care of rendering texts and images for a page (properly decoding them and doing other stuff like that).
