### ISSUE TITLE
Pycrypto is unmaintained and breaks during setup.py install

### ISSUE THREAD

**Issue by cdietschrun** [maxpmaxp/pdfreader#59]
Direct dependency pycrypto is EOL and unmaintained and breaks during install:

https://github.com/pycrypto/pycrypto/issues/310
https://github.com/pycrypto/pycrypto/issues/301

They are trying to EOL pycrypto. There are alternative libraries for crypto that should be used like `cryptography` or `pycryptodome`

**Comment by maxpmaxp** [comment]
@cdietschrun Thank you. Going to switch to `cryptography`

**Comment by maxpmaxp** [comment]
Fixed on master. v0.1.7.dev1
