### ISSUE TITLE
SimpleCanvas.copy converts images dictionary to list

### ISSUE THREAD

**Issue by viking** [maxpmaxp/pdfreader#63]
See https://github.com/maxpmaxp/pdfreader/blob/42444158babe3dc474412c4c8639a875b1f4effe/pdfreader/viewer/canvas.py#L44

If images is an empty dictionary, it gets converted to an empty list.

**Comment by viking** [comment]
Actually, this isn't just happening for empty dictionaries. It happens whenever using CanvasIterator.

**Comment by viking** [comment]
Converting the images dictionary to a list throws away the dictionary values and only keeps the keys.

**Comment by maxpmaxp** [comment]
@viking fixed on master. Feel free submitting PRs next time :-)
