### ISSUE TITLE
Error when trying to read a pdf with Identity-H encoding

### ISSUE THREAD

**Issue by botev** [maxpmaxp/pdfreader#77]
Trying to load a pdf which apparently has an Identity-H encoding I get the error:
```
[Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/pdfreader/codecs/cmaps/Identity-H'
```
I'm seeing that there is potentially a correct codecs folder, but is it possible to install codecs or are there any workarounds for this?

**Comment by maxpmaxp** [comment]
@botev @mstgrant can you share your pdf and your code when you see this error?

**Comment by aleksandar-devedzic** [comment]
I have the same issue, this is my code with pdf example:

```
pdf_link = 'https://www.neerach.ch/public/upload/assets/1417/MTB0321.pdf'
response = requests.get(pdf_link, stream=True)
my_raw_data = response.content

#extract text page by page
with BytesIO(my_raw_data) as data:
    
    viewer = SimplePDFViewer(data)

    # get all pages
    all_pages = [p for p in viewer.doc.pages()]
    total_page_num = len(all_pages)
    
    for page_number in range(1, total_page_num+1):
        viewer.navigate(int(page_number))
        viewer.render()
        page_strings = "".join(viewer.canvas.strings)
        page_strings = page_strings.strip().replace('     ', '\n\n').strip()
        page_strings = page_strings.replace('  ', '\n\n').strip()

        # joining text from all pages
        full_pdf_text += page_strings + '\n\nPage: ' + str(page_number) + ' / ' + str(total_page_num) + '\n\n\n'

    print(full_pdf_text)

```

The error that I get:
`FileNotFoundError: [Errno 2] No such file or directory: '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdfreader/codecs/cmaps/Identity-H'
`
I have tried that other PDF extraction libs and the result that I get is:
`...(cid:57)(cid:72)(cid:85)(cid:75)(cid:68)(cid:81)...
`That some strange type of encoding, but If i translate the numbers to ASCII i do not get the correct chars.

**Comment by maxpmaxp** [comment]
@aleksandar-devedzic I can't reproduce the issue. What `pdfreader` version do you use?

**Comment by maxpmaxp** [comment]
@aleksandar-devedzic I just reproduced it. Working on a patch.

**Comment by maxpmaxp** [comment]
@aleksandar-devedzic can you check v0.1.10 please? Should be good.

**Comment by aleksandar-devedzic** [comment]
I have tried:
sudo pip3 install pdfreader==0.1.10
and
sudo pip3 install pdfreader --upgrade

ERROR: Could not find a version that satisfies the requirement pdfreader==0.1.1
ERROR: Could not find a version that satisfies the requirement pdfreader==0.1.10

**Comment by maxpmaxp** [comment]
@aleksandar-devedzic v0.1.10 is on pypi now https://pypi.org/project/pdfreader/0.1.10/

I've created an issue for the decoding problem you described. See #81
