### ISSUE TITLE
PyPDF2

### ISSUE THREAD

**Issue by MartinThoma** [maxpmaxp/pdfreader#90]
Hi :wave: 

I'm the new maintainer of PyPDF2: https://github.com/py-pdf/PyPDF2

I just stumbled over pdfreader and wondered if you wanted to join PyPDF2 :-) 
It seems that pdfreader supports a subset of PyPDF2.

I'm currently preparing the 2.0 release. As it's a major release, I want to introduce breaking changes that make the overall user / developer experience better: https://github.com/py-pdf/PyPDF2/discussions/752 (e.g. dropping Python 2.7 support; improving interfaces; removing inconsistencies).

**Comment by MartinThoma** [comment]
You have also linked to pyPpdf in the README ([link](https://github.com/maxpmaxp/pdfreader#related-projects)). That project is dead for many years now. PyPDF2 is the one fork that is still alive and has the biggest / most active community.

**Comment by maxpmaxp** [comment]
@MartinThoma I'll update the link. I tried PyPDF2 before starting this project and had multiple issues with non-standard encodings. It was long ago, though :-) 

I think I I could contribute to PyPDF2 when have time.
