### ISSUE TITLE
Allow `PDFDocument` to be used in a context manager declaration

### ISSUE THREAD

**Issue by Xepheryy** [maxpmaxp/pdfreader#92]
### Description
Make use of context managers to write slightly cleaner code for both PDFDocuments and SimplePDFViewers. Currently this is not supported and `AttributeError: __enter__` is displayed as it is not implemented yet.

### Intended usage
``` python
with PDFDocument(open('filepath', 'rb')) as doc:
    print(doc.header.version)
```

### Current usage
``` python
with open('filepath', 'rb') as pdf:
    doc = PDFDocument(pdf)
    print(doc.header.version)
```

> pdfreader Version 0.1.11

**Comment by maxpmaxp** [comment]
Nice suggestion. I'll add this feature when have time. Feel free to contribute btw!

**Comment by maxpmaxp** [comment]
@Xepheryy Fixed on master. Going to be a part of v0.1.12
