### ISSUE TITLE
Failure to extract image as Pillow image (

### ISSUE THREAD

**Issue by lisch** [maxpmaxp/pdfreader#99]
Running the test script on the sample file produces a traceback.

- [test.py](https://github.com/maxpmaxp/pdfreader/files/9162481/test.py.txt)
- [pdfreader-fail-2.pdf](https://github.com/maxpmaxp/pdfreader/files/9162473/pdfreader-fail-2.pdf)
```
Traceback (most recent call last):
  File "./test.py", line 9, in <module>
    image = viewer.canvas.images[name].to_Pillow()
  File "/home/rhlisch/.local/lib/python3.7/site-packages/pdfreader/pillow.py", line 71, in to_Pillow
    my_cs, base_cs, hival, lookup = cs[0], cs[1], cs[2], cs[3].filtered
AttributeError: 'HexString' object has no attribute 'filtered'
```

**Comment by maxpmaxp** [comment]
@lisch Fixed on master. Thanks for reporting! Feel free to contribute btw :-)
